/**
 * Maps country names to their ISO country codes and vice versa.
 * Lookup is case-insensitive (convert to lowercase before lookup).
 */
export const countryNameToId = {
	'usa': 'us',
	'united states': 'us',
	'afghanistan': 'af',
	'albania': 'al',
	'algeria': 'dz',
	'andorra': 'ad',
	'angola': 'ao',
	'antigua and barbuda': 'ag',
	'argentina': 'ar',
	'armenia': 'am',
	'australia': 'au',
	'austria': 'at',
	'azerbaijan': 'az',
	'bahamas': 'bs',
	'bahrain': 'bh',
	'bangladesh': 'bd',
	'barbados': 'bb',
	'belarus': 'by',
	'belgium': 'be',
	'belize': 'bz',
	'benin': 'bj',
	'bhutan': 'bt',
	'bolivia': 'bo',
	'bosnia and herzegovina': 'ba',
	'botswana': 'bw',
	'brazil': 'br',
	'brunei': 'bn',
	'bulgaria': 'bg',
	'burkina faso': 'bf',
	'burundi': 'bi',
	'cambodia': 'kh',
	'cameroon': 'cm',
	'canada': 'ca',
	'cape verde': 'cv',
	'central african republic': 'cf',
	'chad': 'td',
	'chile': 'cl',
	'china': 'cn',
	'colombia': 'co',
	'comoros': 'km',
	'congo': 'cg',
	'congo (democratic republic)': 'cd',
	'costa rica': 'cr',
	'côte d\'ivoire': 'ci',
	'croatia': 'hr',
	'cuba': 'cu',
	'cyprus': 'cy',
	'czech republic': 'cz',
	'denmark': 'dk',
	'djibouti': 'dj',
	'dominica': 'dm',
	'dominican republic': 'do',
	'ecuador': 'ec',
	'egypt': 'eg',
	'el salvador': 'sv',
	'equatorial guinea': 'gq',
	'eritrea': 'er',
	'estonia': 'ee',
	'ethiopia': 'et',
	'fiji': 'fj',
	'finland': 'fi',
	'france': 'fr',
	'gabon': 'ga',
	'gambia': 'gm',
	'georgia': 'ge',
	'germany': 'de',
	'ghana': 'gh',
	'greece': 'gr',
	'grenada': 'gd',
	'guatemala': 'gt',
	'guinea': 'gn',
	'guinea-bissau': 'gw',
	'guyana': 'gy',
	'haiti': 'ht',
	'honduras': 'hn',
	'hungary': 'hu',
	'iceland': 'is',
	'india': 'in',
	'indonesia': 'id',
	'iran': 'ir',
	'iraq': 'iq',
	'ireland': 'ie',
	'israel': 'il',
	'italy': 'it',
	'jamaica': 'jm',
	'japan': 'jp',
	'jordan': 'jo',
	'kazakhstan': 'kz',
	'kenya': 'ke',
	'kiribati': 'ki',
	'korea (north)': 'kp',
	'korea (south)': 'kr',
	'kuwait': 'kw',
	'kyrgyzstan': 'kg',
	'laos': 'la',
	'latvia': 'lv',
	'lebanon': 'lb',
	'lesotho': 'ls',
	'liberia': 'lr',
	'libya': 'ly',
	'liechtenstein': 'li',
	'lithuania': 'lt',
	'luxembourg': 'lu',
	'macedonia': 'mk',
	'madagascar': 'mg',
	'malawi': 'mw',
	'malaysia': 'my',
	'maldives': 'mv',
	'mali': 'ml',
	'malta': 'mt',
	'marshall islands': 'mh',
	'mauritania': 'mr',
	'mauritius': 'mu',
	'mexico': 'mx',
	'micronesia': 'fm',
	'moldova': 'md',
	'monaco': 'mc',
	'mongolia': 'mn',
	'montenegro': 'me',
	'morocco': 'ma',
	'mozambique': 'mz',
	'myanmar': 'mm',
	'namibia': 'na',
	'nauru': 'nr',
	'nepal': 'np',
	'netherlands': 'nl',
	'new zealand': 'nz',
	'nicaragua': 'ni',
	'niger': 'ne',
	'nigeria': 'ng',
	'norway': 'no',
	'oman': 'om',
	'pakistan': 'pk',
	'palau': 'pw',
	'panama': 'pa',
	'papua new guinea': 'pg',
	'paraguay': 'py',
	'peru': 'pe',
	'philippines': 'ph',
	'poland': 'pl',
	'portugal': 'pt',
	'qatar': 'qa',
	'romania': 'ro',
	'russia': 'ru',
	'rwanda': 'rw',
	'saint kitts and nevis': 'kn',
	'saint lucia': 'lc',
	'saint vincent and the grenadines': 'vc',
	'samoa': 'ws',
	'san marino': 'sm',
	'são tomé and príncipe': 'st',
	'saudi arabia': 'sa',
	'senegal': 'sn',
	'serbia': 'rs',
	'seychelles': 'sc',
	'sierra leone': 'sl',
	'singapore': 'sg',
	'slovakia': 'sk',
	'slovenia': 'si',
	'solomon islands': 'sb',
	'somalia': 'so',
	'south africa': 'za',
	'south sudan': 'ss',
	'spain': 'es',
	'sri lanka': 'lk',
	'sudan': 'sd',
	'suriname': 'sr',
	'swaziland': 'sz',
	'sweden': 'se',
	'switzerland': 'ch',
	'syria': 'sy',
	'taiwan': 'tw',
	'tajikistan': 'tj',
	'tanzania': 'tz',
	'thailand': 'th',
	'timor-leste': 'tl',
	'togo': 'tg',
	'tonga': 'to',
	'trinidad and tobago': 'tt',
	'tunisia': 'tn',
	'turkey': 'tr',
	'turkmenistan': 'tm',
	'tuvalu': 'tv',
	'uganda': 'ug',
	'ukraine': 'ua',
	'united arab emirates': 'ae',
	'united kingdom': 'gb',
	'uruguay': 'uy',
	'uzbekistan': 'uz',
	'vanuatu': 'vu',
	'vatican city': 'va',
	'venezuela': 've',
	'vietnam': 'vn',
	'yemen': 'ye',
	'zambia': 'zm',
	'zimbabwe': 'zw',
};

export const countryIdToName = {
	// United States variations
	'us': 'United States',
	'usa': 'United States',
	// All other country codes to names
	'af': 'Afghanistan',
	'al': 'Albania',
	'dz': 'Algeria',
	'ad': 'Andorra',
	'ao': 'Angola',
	'ag': 'Antigua and Barbuda',
	'ar': 'Argentina',
	'am': 'Armenia',
	'au': 'Australia',
	'at': 'Austria',
	'az': 'Azerbaijan',
	'bs': 'Bahamas',
	'bh': 'Bahrain',
	'bd': 'Bangladesh',
	'bb': 'Barbados',
	'by': 'Belarus',
	'be': 'Belgium',
	'bz': 'Belize',
	'bj': 'Benin',
	'bt': 'Bhutan',
	'bo': 'Bolivia',
	'ba': 'Bosnia and Herzegovina',
	'bw': 'Botswana',
	'br': 'Brazil',
	'bn': 'Brunei',
	'bg': 'Bulgaria',
	'bf': 'Burkina Faso',
	'bi': 'Burundi',
	'kh': 'Cambodia',
	'cm': 'Cameroon',
	'ca': 'Canada',
	'cv': 'Cape Verde',
	'cf': 'Central African Republic',
	'td': 'Chad',
	'cl': 'Chile',
	'cn': 'China',
	'co': 'Colombia',
	'km': 'Comoros',
	'cg': 'Congo',
	'cd': 'Congo (Democratic Republic)',
	'cr': 'Costa Rica',
	'ci': 'Côte d\'Ivoire',
	'hr': 'Croatia',
	'cu': 'Cuba',
	'cy': 'Cyprus',
	'cz': 'Czech Republic',
	'dk': 'Denmark',
	'dj': 'Djibouti',
	'dm': 'Dominica',
	'do': 'Dominican Republic',
	'ec': 'Ecuador',
	'eg': 'Egypt',
	'sv': 'El Salvador',
	'gq': 'Equatorial Guinea',
	'er': 'Eritrea',
	'ee': 'Estonia',
	'et': 'Ethiopia',
	'fj': 'Fiji',
	'fi': 'Finland',
	'fr': 'France',
	'ga': 'Gabon',
	'gm': 'Gambia',
	'ge': 'Georgia',
	'de': 'Germany',
	'gh': 'Ghana',
	'gr': 'Greece',
	'gd': 'Grenada',
	'gt': 'Guatemala',
	'gn': 'Guinea',
	'gw': 'Guinea-Bissau',
	'gy': 'Guyana',
	'ht': 'Haiti',
	'hn': 'Honduras',
	'hu': 'Hungary',
	'is': 'Iceland',
	'in': 'India',
	'id': 'Indonesia',
	'ir': 'Iran',
	'iq': 'Iraq',
	'ie': 'Ireland',
	'il': 'Israel',
	'it': 'Italy',
	'jm': 'Jamaica',
	'jp': 'Japan',
	'jo': 'Jordan',
	'kz': 'Kazakhstan',
	'ke': 'Kenya',
	'ki': 'Kiribati',
	'kp': 'Korea (North)',
	'kr': 'Korea (South)',
	'kw': 'Kuwait',
	'kg': 'Kyrgyzstan',
	'la': 'Laos',
	'lv': 'Latvia',
	'lb': 'Lebanon',
	'ls': 'Lesotho',
	'lr': 'Liberia',
	'ly': 'Libya',
	'li': 'Liechtenstein',
	'lt': 'Lithuania',
	'lu': 'Luxembourg',
	'mk': 'Macedonia',
	'mg': 'Madagascar',
	'mw': 'Malawi',
	'my': 'Malaysia',
	'mv': 'Maldives',
	'ml': 'Mali',
	'mt': 'Malta',
	'mh': 'Marshall Islands',
	'mr': 'Mauritania',
	'mu': 'Mauritius',
	'mx': 'Mexico',
	'fm': 'Micronesia',
	'md': 'Moldova',
	'mc': 'Monaco',
	'mn': 'Mongolia',
	'me': 'Montenegro',
	'ma': 'Morocco',
	'mz': 'Mozambique',
	'mm': 'Myanmar',
	'na': 'Namibia',
	'nr': 'Nauru',
	'np': 'Nepal',
	'nl': 'Netherlands',
	'nz': 'New Zealand',
	'ni': 'Nicaragua',
	'ne': 'Niger',
	'ng': 'Nigeria',
	'no': 'Norway',
	'om': 'Oman',
	'pk': 'Pakistan',
	'pw': 'Palau',
	'pa': 'Panama',
	'pg': 'Papua New Guinea',
	'py': 'Paraguay',
	'pe': 'Peru',
	'ph': 'Philippines',
	'pl': 'Poland',
	'pt': 'Portugal',
	'qa': 'Qatar',
	'ro': 'Romania',
	'ru': 'Russia',
	'rw': 'Rwanda',
	'kn': 'Saint Kitts and Nevis',
	'lc': 'Saint Lucia',
	'vc': 'Saint Vincent and the Grenadines',
	'ws': 'Samoa',
	'sm': 'San Marino',
	'st': 'São Tomé and Príncipe',
	'sa': 'Saudi Arabia',
	'sn': 'Senegal',
	'rs': 'Serbia',
	'sc': 'Seychelles',
	'sl': 'Sierra Leone',
	'sg': 'Singapore',
	'sk': 'Slovakia',
	'si': 'Slovenia',
	'sb': 'Solomon Islands',
	'so': 'Somalia',
	'za': 'South Africa',
	'ss': 'South Sudan',
	'es': 'Spain',
	'lk': 'Sri Lanka',
	'sd': 'Sudan',
	'sr': 'Suriname',
	'sz': 'Swaziland',
	'se': 'Sweden',
	'ch': 'Switzerland',
	'sy': 'Syria',
	'tw': 'Taiwan',
	'tj': 'Tajikistan',
	'tz': 'Tanzania',
	'th': 'Thailand',
	'tl': 'Timor-Leste',
	'tg': 'Togo',
	'to': 'Tonga',
	'tt': 'Trinidad and Tobago',
	'tn': 'Tunisia',
	'tr': 'Turkey',
	'tm': 'Turkmenistan',
	'tv': 'Tuvalu',
	'ug': 'Uganda',
	'ua': 'Ukraine',
	'ae': 'United Arab Emirates',
	'gb': 'United Kingdom',
	'uk': 'United Kingdom',
	'uy': 'Uruguay',
	'uz': 'Uzbekistan',
	'vu': 'Vanuatu',
	'va': 'Vatican City',
	've': 'Venezuela',
	'vn': 'Vietnam',
	'ye': 'Yemen',
	'zm': 'Zambia',
	'zw': 'Zimbabwe',
};

