/**
 * Maps entity type names to their standardized IDs.
 * Lookup is case-insensitive (convert to lowercase before lookup).
 */
export const entityTypeNameToId = {
	'limited liability company': 'Limited Liability Company',
	'corporation': 'Corporation',
	'charitable, non-profit corporation': 'Charitable, Non-profit Corporation',
	'municipal corporation': 'Municipal Corporation',
	'non-profit corporation': 'Non-profit Corporation',
	'professional corporation': 'Professional Corporation',
	'joint stock company': 'Joint Stock Company',
	'partnership': 'Partnership',
	'limited partnership': 'Limited Partnership',
	'sole proprietorship': 'Sole Proprietorship',
	'trust': 'Trust',
	'estate': 'Estate',
	'state agency': 'State Agency',
	'non-profit association': 'Non-profit Association',
	'charitable corporation': 'Charitable Corporation',
	'cooperative corporation': 'Cooperative Corporation',
	'non-stock corporation': 'Non-stock Corporation',
	'public benefit corporation': 'Public Benefit Corporation',
	'tax exempt corporation': 'Tax Exempt Corporation',
	'cooperative association': 'Cooperative Association',
	'incorporated association': 'Incorporated Association',
	'unincorporated association': 'Unincorporated Association',
	'federally-recognized indian tribe': 'Federally-recognized Indian Tribe',
	'state-recognized indian tribe': 'State-recognized Indian Tribe',
	'stock company': 'Stock Company',
	'congressionally chartered non-profit organization': 'Congressionally Chartered Non-profit Organization',
	'joint venture': 'Joint Venture',
	'joint ownership': 'Joint Ownership',
	'federally chartered credit union': 'Federally Chartered Credit Union',
	'credit union': 'Credit Union',
	'chartered bank': 'Chartered Bank',
	'national banking association': 'National Banking Association',
	'body politic and corporate': 'Body Politic and Corporate',
	'state university': 'State University',
	'federal agency': 'Federal Agency',
	'agency of the united states government': 'Agency of the United States government',
	'instrumentality': 'Instrumentality',
	'foundation': 'Foundation',
	'trustee': 'Trustee',
	'business trust': 'Business Trust',
	'charitable trust': 'Charitable Trust',
	'entity not listed': 'Entity not listed',
	'individual': 'individual',
};
