/**
 * Maps US state names to their abbreviations.
 * Lookup is case-insensitive (convert to lowercase before lookup).
 */
export const stateNameToId = {
	'alabama': 'al',
	'alaska': 'ak',
	'american samoa': 'as',
	'arizona': 'az',
	'arkansas': 'ar',
	'california': 'ca',
	'colorado': 'co',
	'connecticut': 'ct',
	'delaware': 'de',
	'district of columbia': 'dc',
	'florida': 'fl',
	'georgia': 'ga',
	'guam': 'gu',
	'hawaii': 'hi',
	'idaho': 'id',
	'illinois': 'il',
	'indiana': 'in',
	'iowa': 'ia',
	'kansas': 'ks',
	'kentucky': 'ky',
	'louisiana': 'la',
	'maine': 'me',
	'maryland': 'md',
	'massachusetts': 'ma',
	'michigan': 'mi',
	'minnesota': 'mn',
	'mississippi': 'ms',
	'missouri': 'mo',
	'montana': 'mt',
	'nebraska': 'ne',
	'nevada': 'nv',
	'new hampshire': 'nh',
	'new jersey': 'nj',
	'new mexico': 'nm',
	'new york': 'ny',
	'north carolina': 'nc',
	'north dakota': 'nd',
	'northern mariana islands': 'mp',
	'ohio': 'oh',
	'oklahoma': 'ok',
	'oregon': 'or',
	'pennsylvania': 'pa',
	'puerto rico': 'pr',
	'rhode island': 'ri',
	'south carolina': 'sc',
	'south dakota': 'sd',
	'tennessee': 'tn',
	'texas': 'tx',
	'united states minor outlying islands': 'um',
	'utah': 'ut',
	'vermont': 'vt',
	'virgin islands, u.s.': 'vi',
	'virginia': 'va',
	'washington': 'wa',
	'west virginia': 'wv',
	'wisconsin': 'wi',
	'wyoming': 'wy',
	'armed forces in americas excluding canada': 'af_americas',
	'armed forces in europe, the middle east, africa, and canada': 'af_europe',
	'armed forces in the pacific': 'af_pacific',
};

