/**
 * Maps US state names to their abbreviations.
 * Lookup is case-insensitive (convert to lowercase before lookup).
 */
export const stateNameToId = {
	'alabama': 'al',
	'alaska': 'ak',
	'american samoa': 'as',
	'arizona': 'az',
	'arkansas': 'ar',
	'california': 'ca',
	'colorado': 'co',
	'connecticut': 'ct',
	'delaware': 'de',
	'district of columbia': 'dc',
	'florida': 'fl',
	'georgia': 'ga',
	'guam': 'gu',
	'hawaii': 'hi',
	'idaho': 'id',
	'illinois': 'il',
	'indiana': 'in',
	'iowa': 'ia',
	'kansas': 'ks',
	'kentucky': 'ky',
	'louisiana': 'la',
	'maine': 'me',
	'maryland': 'md',
	'massachusetts': 'ma',
	'michigan': 'mi',
	'minnesota': 'mn',
	'mississippi': 'ms',
	'missouri': 'mo',
	'montana': 'mt',
	'nebraska': 'ne',
	'nevada': 'nv',
	'new hampshire': 'nh',
	'new jersey': 'nj',
	'new mexico': 'nm',
	'new york': 'ny',
	'north carolina': 'nc',
	'north dakota': 'nd',
	'northern mariana islands': 'mp',
	'ohio': 'oh',
	'oklahoma': 'ok',
	'oregon': 'or',
	'pennsylvania': 'pa',
	'puerto rico': 'pr',
	'rhode island': 'ri',
	'south carolina': 'sc',
	'south dakota': 'sd',
	'tennessee': 'tn',
	'texas': 'tx',
	'united states minor outlying islands': 'um',
	'utah': 'ut',
	'vermont': 'vt',
	'virgin islands, u.s.': 'vi',
	'virginia': 'va',
	'washington': 'wa',
	'west virginia': 'wv',
	'wisconsin': 'wi',
	'wyoming': 'wy',
	'armed forces in americas excluding canada': 'af_americas',
	'armed forces in europe, the middle east, africa, and canada': 'af_europe',
	'armed forces in the pacific': 'af_pacific',
};

/**
 * Reverse map from state abbreviation to full state name.
 * Lookup is case-insensitive.
 */
export const stateIdToName = {
	'al': 'Alabama',
	'ak': 'Alaska',
	'as': 'American Samoa',
	'az': 'Arizona',
	'ar': 'Arkansas',
	'ca': 'California',
	'co': 'Colorado',
	'ct': 'Connecticut',
	'de': 'Delaware',
	'dc': 'District of Columbia',
	'fl': 'Florida',
	'ga': 'Georgia',
	'gu': 'Guam',
	'hi': 'Hawaii',
	'id': 'Idaho',
	'il': 'Illinois',
	'in': 'Indiana',
	'ia': 'Iowa',
	'ks': 'Kansas',
	'ky': 'Kentucky',
	'la': 'Louisiana',
	'me': 'Maine',
	'md': 'Maryland',
	'ma': 'Massachusetts',
	'mi': 'Michigan',
	'mn': 'Minnesota',
	'ms': 'Mississippi',
	'mo': 'Missouri',
	'mt': 'Montana',
	'ne': 'Nebraska',
	'nv': 'Nevada',
	'nh': 'New Hampshire',
	'nj': 'New Jersey',
	'nm': 'New Mexico',
	'ny': 'New York',
	'nc': 'North Carolina',
	'nd': 'North Dakota',
	'mp': 'Northern Mariana Islands',
	'oh': 'Ohio',
	'ok': 'Oklahoma',
	'or': 'Oregon',
	'pa': 'Pennsylvania',
	'pr': 'Puerto Rico',
	'ri': 'Rhode Island',
	'sc': 'South Carolina',
	'sd': 'South Dakota',
	'tn': 'Tennessee',
	'tx': 'Texas',
	'um': 'United States Minor Outlying Islands',
	'ut': 'Utah',
	'vt': 'Vermont',
	'vi': 'Virgin Islands, U.S.',
	'va': 'Virginia',
	'wa': 'Washington',
	'wv': 'West Virginia',
	'wi': 'Wisconsin',
	'wy': 'Wyoming',
	'af_americas': 'Armed Forces in Americas excluding Canada',
	'af_europe': 'Armed Forces in Europe, the Middle East, Africa, and Canada',
	'af_pacific': 'Armed Forces in the Pacific',
};

/**
 * Converts a state abbreviation to its full name.
 * @param {string} stateId - The state abbreviation (e.g., "CA")
 * @returns {string|null} The full state name (e.g., "California") or null if not found
 */
export const getStateNameById = (stateId) => {
	if (!stateId) return null;
	const lowerCaseId = stateId.toLowerCase();
	return stateIdToName[lowerCaseId] || null;
};

